### ISSUE TITLE
Proxy not working when i set AD_TAG

### ISSUE THREAD

**Issue by FelinaHD** [alexbers/mtprotoproxy#10]
Hi, When AD_TAG is set proxy not working anymore...

```
PORT = 3259

# name -> secret (32 hex chars)
USERS = {
    "tg":  "0123456789abcdef0123456789abcdef"
}

# Tag for advertising, obtainable from @MTProxybot

AD_TAG = "02b86204e28dfceda581080dd966179c"
```

**Comment by alexbers** [comment]
Hi, I checked a proxy with this config and it works for me. 

Do your server is behind NAT?
After launch the proxy should tell the ip address tg://proxy?server=<IP_ADDR>&port=3259&secret=0123456789abcdef0123456789abcdef

Does this ip address is the same as your external address?

Also, it is interesting on which platform the telegram client is running: ios/android/windows.

**Comment by alexbers** [comment]
If you have other servers, please, check this config on them.

**Comment by FelinaHD** [comment]
it works ok and i connected succesfuly when AD_TAG is not set.

this is works for me:
PORT = 3259

```
# name -> secret (32 hex chars)
USERS = {
    "tg":  "0123456789abcdef0123456789abcdef"
}

# Tag for advertising, obtainable from @MTProxybot

#AD_TAG = "02b86204e28dfceda581080dd966179c"
```

this is not working:
```
# name -> secret (32 hex chars)
USERS = {
    "tg":  "0123456789abcdef0123456789abcdef"
}

# Tag for advertising, obtainable from @MTProxybot

AD_TAG = "02b86204e28dfceda581080dd966179c"
```

**Comment by p1ratrulezzz** [comment]
Send the log of what you got when run the daemon.
Yesterday I had same issue and it was because daemon sent ipv6 address to telegram clients as I understood. Disabling ipv6 using sysctl helped.

**Comment by alexbers** [comment]
When you enable advertising, other servers are used for communication to pass AD_TAG. The protocol of communication with that other servers requires knowing your current external ip. One of the reason the configuration with tags doesn't work is a problem with external ip determination. That is why I asked to check if external ip is detected properly in string
tg://proxy?server=<IP_ADDR>&port=3259&secret=0123456789abcdef0123456789abcdef

Also, it your server is behind NAT and NAT equipment changes the source port, it won't work (official proxy also likely won't work in this case).

**Comment by alexbers** [comment]
The problems with ipv6 on the proxy side should be solved today.

I was planing to add ipv6 connection capability between the proxy and middleware proxies - the thing that official client still can't do. To find ipv6 addresses of them I scanned the telegram network. I managed to find 5 hosts which listen port 8888 (e.g. 2001:b28:f23f:f005::d), but they drop a connection just after connecting to them. But I hope they will be available soon.

**Comment by p1ratrulezzz** [comment]
Check here https://github.com/danog/MadelineProto/blob/2fdb33d2e4574e866a37dab7b3120e9f6ea6fd89/src/danog/MadelineProto/MTProto.php 
There are a lot of addresses

**Comment by alexbers** [comment]
Ok, I'll check, thanks

**Comment by alexbers** [comment]
I found the addresses and now the proxy should fully support ipv6 both for listening and for external connections. As far as I know no other proxy, including the official one, doesn't support ipv6 for external connections yet.

**Comment by p1ratrulezzz** [comment]
As for me OK now. Works without any other dance with a tambourine

**Comment by mgdz** [comment]
without ad_tag worked fine, with tag - not worked. vscale.io, ipv6 disabled.
middle_proxies_v4 available:
64 bytes from 149.154.175.50: icmp_seq=1 ttl=56 time=147 ms
64 bytes from 149.154.162.38: icmp_seq=1 ttl=57 time=40.4 ms
64 bytes from 149.154.175.100: icmp_seq=1 ttl=55 time=149 ms
64 bytes from 91.108.4.136: icmp_seq=1 ttl=59 time=41.5 ms
64 bytes from 91.108.56.181: icmp_seq=1 ttl=55 time=200 ms

**Comment by alexbers** [comment]
I ordered a server in vscale.io to reproduce the bug. There are some connection problems with telegram  second datacenter: 149.154.162.38:80 - the connection attempts fail. May be the hosting blocks those packets, or Telegram's second datacenter doesn't accept connections from vscale. 

Anyway, please try to use other hostings, preferably not in Russia or Iran.

**Comment by seega** [comment]
@mgdz ping is not proof of availability, servers work with ipv6 in Russia.

**Comment by p1ratrulezzz** [comment]
Yes. check at least with curl

**Comment by madl-ash** [comment]
@FelinaHD @alexbers when AD_TAG is set,android clients cannot download media(images).should i make a new issue for this?

**Comment by alexbers** [comment]
Yes, it would be good

**Comment by Quarx2k** [comment]
Same problem. With AD_TAG proxy works only on Android, but PC client cant connect.

**Comment by alexbers** [comment]
It seems the telegram updated some logic on a server. I am fixing this

**Comment by alexbers** [comment]
Could you try to retry with the latest version (stable or master), the https://github.com/alexbers/mtprotoproxy/commit/0d0a334e8669f6c1e267153abdcc2f255db5ac2e should solve this

**Comment by Quarx2k** [comment]
PC now works, but both mobile clients can;t connect. :(

**Comment by alexbers** [comment]
Could you try one more time with the latest version, the https://github.com/alexbers/mtprotoproxy/commit/142c974333d3752211faeca1070338e7b860ad20 should solve this, at least on my tests

**Comment by Quarx2k** [comment]
PC and Android works now, but Telegram X still can't connect.

**Comment by HirbodBehnam** [comment]
What is your Telegram X version?

**Comment by alexbers** [comment]
Quarx2k: could you test the latest version of the program in master branch. The https://github.com/alexbers/mtprotoproxy/commit/a6e39a66d160de5055232c35f5fd7fa6e85697be should fix work in the Telegram X

**Comment by Quarx2k** [comment]
Works fine on all client! Thanks :)

**Comment by alexbers** [comment]
Thanks to @K900, who implemented the intermediate version of the protocol.

**Comment by matshch** [comment]
We still getting same issues with latest version.

**Comment by alexbers** [comment]
Are you using the master branch?

**Comment by matshch** [comment]
Yes, of course. We tried a6e39a66d160de5055232c35f5fd7fa6e85697be and dc9da63fbcb1839b2281a4f4aae9b4629c7fd78c, both not working when we enable AD_TAG in `config.py`.

**Comment by alexbers** [comment]
does it work for some clients or not work at all? Which client version are you using?

**Comment by matshch** [comment]
Not working at all: tested Telegram Desktop, Telegram Android Beta, Telegram X Android Beta.
It's under NAT, external IP resolved right, and everything works when AD_TAG is commented.

**Comment by alexbers** [comment]
Please, check the time on your server - it should be precise. It could be one of the reasons why the proxy doesn't works. Another reason is the firewall settings

**Comment by matshch** [comment]
Looks like time is not a problem. Maybe that's a NAT: we will try to give our proxy separate IP.

**Comment by Mohamadrezanakhleh** [comment]
same problem here, with AD_TAG, no client can connect.

**Comment by alexbers** [comment]
please also check the time on your server. And, please, check if the external IP resolved right

**Comment by alexbers** [comment]
you can check the obtain ip on the https://www.whatismyip.com/ site. Then the ip can be compared with the ip in the proxy's output.

**Comment by Mohamadrezanakhleh** [comment]
Your Public IPv4 is: 164.X.X.11
Your IPv6 is: Not Detected
Your Local IP is: 164.X.X.11
Location: Roubaix, HDF FR 
ISP: OVH SAS


this IP is the same as shown by Python app. so it sounds no problem with IP too.
but I have noticed something:
1-when I run the Python app sometimes (1 out of 10 tries) it says "can not determine your UP address and Ad is disabled but after I restart the app the IP resolves correctly
2-when  I run the Python app with Ad_tag on the client side, It says connecting and then says updating for maybe 100ms and then again connecting and this continuous for like 5 minutes and then not updating at all.

**Comment by alexbers** [comment]
The proxy with ad tries to get your ip address on http://ipv4.myexternalip.com/raw and if the proxy failed, the "can not determine your IP address" message is shown. This can occur if your internet connection is  unstable. You can check it on manually going to http://ipv4.myexternalip.com/raw address and to other addresses.

If you are using Windows OS, please check your firewall connection.

Also you can try different hosting providers, may be this one is blocking telegram networks.

**Comment by alexbers** [comment]
Also in the short time I will implement the support for the other ip resolving services. May be this one is unstable

**Comment by alexbers** [comment]
The support for other ip resolving services is implemented. Now it should be more reliable on unstable internet connection: https://github.com/alexbers/mtprotoproxy/commit/47218748aa1d5efdf94db19dd8e56e869bc8ba64

Could you please retry with the latest proxy from master.

**Comment by Mohamadrezanakhleh** [comment]
I changed  the IPS provider.
Again the same problem.
There must be a problem  with  protocol  implementation i think. 
IP get resolved  right most of the time and while then  proxy  with  AD_TAG doesn't work too.
I am going  to test the new version  short and i ll let you know.
Thanks for your  answers

**Comment by Mohamadrezanakhleh** [comment]
If you  want  i can give  you access to  my VPS to troubleshoot the  problem.

**Comment by alexbers** [comment]
ok, i am @bay3255 in tg
